// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 構造の変更は直接接続で行う（プール経由だと不具合が出ることがある）
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
